---
- hosts: all
  gather_facts: no
  tasks:
  - name: Criando Pasta Kaizen e Subpastas
    win_file:
      path: '{{ item }}'
      state: directory
    loop:
    - "C:\\Warley Ansible"
    - "C:\\Warley Ansible\\Instaladores"
    - "C:\\Warley Ansible\\KS-Integration"
    - "C:\\Warley Ansibles\\KS-Mob"
    - "C:\\Warley Ansible\\KS-Service"
    - "C:\\Warley Ansible\\KS-Tools"
    - "C:\\Warley Ansible\\KS-BD"
